export const VERSES = {
  en: [
    { text: '"Commit to the LORD whatever you do, and he will establish your plans."', ref: 'Proverbs 16:3' },
    { text: '"For where your treasure is, there your heart will be also."', ref: 'Matthew 6:21' },
    { text: '"The plans of the diligent lead to profit."', ref: 'Proverbs 21:5' },
    { text: '"Bring the whole tithe into the storehouse."', ref: 'Malachi 3:10' },
    { text: '"Give, and it will be given to you."', ref: 'Luke 6:38' },
    { text: '"Godliness with contentment is great gain."', ref: '1 Timothy 6:6' },
    { text: '"The borrower is servant to the lender."', ref: 'Proverbs 22:7' },
  ],
  es: [
    { text: '"Pon en manos del Señor todas tus obras, y tus proyectos se cumplirán."', ref: 'Proverbios 16:3' },
    { text: '"Porque donde esté tu tesoro, allí estará también tu corazón."', ref: 'Mateo 6:21' },
    { text: '"Los planes del diligente ciertamente llevan a la abundancia."', ref: 'Proverbios 21:5' },
    { text: '"Traigan el diezmo completo al tesoro del templo."', ref: 'Malaquías 3:10' },
    { text: '"Den, y se les dará."', ref: 'Lucas 6:38' },
    { text: '"La piedad con contentamiento es gran ganancia."', ref: '1 Timoteo 6:6' },
    { text: '"El que pide prestado es siervo del que presta."', ref: 'Proverbios 22:7' },
  ],
  fr: [
    { text: '"Confie au Seigneur tout ce que tu fais, et tes projets se réaliseront."', ref: 'Proverbes 16:3' },
    { text: '"Car là où est ton trésor, là aussi sera ton cœur."', ref: 'Matthieu 6:21' },
    { text: '"Les projets du diligent mènent sûrement à l\'abondance."', ref: 'Proverbes 21:5' },
    { text: '"Apportez toute la dîme dans le trésor du temple."', ref: 'Malachie 3:10' },
    { text: '"Donnez, et il vous sera donné."', ref: 'Luc 6:38' },
    { text: '"La piété accompagnée de contentement est une grande source de gain."', ref: '1 Timothée 6:6' },
    { text: '"L\'emprunteur est l\'esclave du prêteur."', ref: 'Proverbes 22:7' },
  ],
  pt: [
    { text: '"Confie ao Senhor tudo o que você faz, e seus planos serão bem-sucedidos."', ref: 'Provérbios 16:3' },
    { text: '"Pois onde estiver o teu tesouro, aí também estará o teu coração."', ref: 'Mateus 6:21' },
    { text: '"Os planos do diligente levam certamente à prosperidade."', ref: 'Provérbios 21:5' },
    { text: '"Trazei todos os dízimos à casa do tesouro."', ref: 'Malaquias 3:10' },
    { text: '"Dai e ser-vos-á dado."', ref: 'Lucas 6:38' },
    { text: '"A piedade com contentamento é grande ganho."', ref: '1 Timóteo 6:6' },
    { text: '"O devedor é escravo do credor."', ref: 'Provérbios 22:7' },
  ],
  sw: [
    { text: '"Mkabidhi BWANA kila unachofanya, na mipango yako itafanikiwa."', ref: 'Mithali 16:3' },
    { text: '"Kwa maana hazina yako ilipo, moyo wako utakuwepo pia."', ref: 'Mathayo 6:21' },
    { text: '"Mipango ya mwenye bidii husababisha faida."', ref: 'Mithali 21:5' },
    { text: '"Leteni zaka zote ghalani."', ref: 'Malaki 3:10' },
    { text: '"Toeni, nanyi mtapewa."', ref: 'Luka 6:38' },
    { text: '"Utauwa pamoja na kuridhika ni faida kubwa."', ref: '1 Timotheo 6:6' },
    { text: '"Mkopaji ni mtumwa wa mkopeshaji."', ref: 'Mithali 22:7' },
  ],
  yo: [
    { text: '"Fi gbogbo iṣẹ rẹ lelẹ fun Oluwa, awọn ero rẹ yoo si ṣe rere."', ref: 'Owe 16:3' },
    { text: '"Nitori ibiti iṣura rẹ wà, ọkan rẹ yoo tun wà nibẹ."', ref: 'Mátíù 6:21' },
    { text: '"Awọn ero ti olùgbiyanjú yorisi anfaani."', ref: 'Owe 21:5' },
    { text: '"Mu gbogbo ẹẹwọ wá si ile-iṣura."', ref: 'Malaki 3:10' },
    { text: '"Fun, a o si fun yín."', ref: 'Luku 6:38' },
    { text: '"Ẹsin pẹlu itẹlọrun ni ere nla."', ref: '1 Timoteu 6:6' },
    { text: '"Ẹni ti o ya jẹ ẹrú ti ẹni ti o yani."', ref: 'Owe 22:7' },
  ],
  ig: [
    { text: '"Tụfuo ihe niile i na-eme n\'aka Chineke, ọ ga-emesi oru gị."', ref: 'Ihe Ochie 16:3' },
    { text: '"Ebe ihe ndị i dere aka nọ, obi gị ga-adi ebe ahụ."', ref: 'Matiu 6:21' },
    { text: '"Atụmatụ onye na-arụ ọrụ na-eduga n\'ọgaranya."', ref: 'Ihe Ochie 21:5' },
    { text: '"Wetara udo niile n\'ụlọ akụ."', ref: 'Malaki 3:10' },
    { text: '"Nye, a ga-enye gị."', ref: 'Luk 6:38' },
    { text: '"Ịtọ Chukwu n\'obi ụtọ bụ uru ọnụ."', ref: '1 Timoti 6:6' },
    { text: '"Onye na-agweta ego bụ ohu nke onye na-agba ya ego."', ref: 'Ihe Ochie 22:7' },
  ],
  ha: [
    { text: '"Ka ba wa Ubangiji duk abin da kake yi, shirye-shiryenka za su yi nasara."', ref: 'Karin Magana 16:3' },
    { text: '"Domin inda dukiyarka take, zuciyarka ma za ta kasance a can."', ref: 'Matiyu 6:21' },
    { text: '"Shirye-shiryen mai himma na kai zuwa ga riba."', ref: 'Karin Magana 21:5' },
    { text: '"Ku kawo cikakkiyar zakka a gidan baitulmalin."', ref: 'Malaki 3:10' },
    { text: '"Ku ba da, za a ba ku."', ref: 'Luka 6:38' },
    { text: '"Tsoron Allah da gamsuwa babban riba ne."', ref: '1 Timoti 6:6' },
    { text: '"Mai bashi bawan mai ba shi ne."', ref: 'Karin Magana 22:7' },
  ],
  zh: [
    { text: '"你所做的事要交托耶和华，你所谋的就必成立。"', ref: '箴言 16:3' },
    { text: '"因为你的财宝在哪里，你的心也在那里。"', ref: '马太福音 6:21' },
    { text: '"殷勤筹划的，足致丰裕。"', ref: '箴言 21:5' },
    { text: '"你们要将当纳的十分之一，全然送入仓库。"', ref: '玛拉基书 3:10' },
    { text: '"你们要给人，就必有给你们的。"', ref: '路加福音 6:38' },
    { text: '"然而，敬虔加上知足的心便是大利了。"', ref: '提摩太前书 6:6' },
    { text: '"借贷的是贷者的仆人。"', ref: '箴言 22:7' },
  ],
  hi: [
    { text: '"अपने सब कामों को यहोवा को सौंप दे, तो तेरी योजनाएँ सफल होंगी।"', ref: 'नीतिवचन 16:3' },
    { text: '"क्योंकि जहाँ तेरा खजाना है, वहीं तेरा मन भी लगा रहेगा।"', ref: 'मत्ती 6:21' },
    { text: '"परिश्रमी की योजनाएँ निश्चित रूप से लाभ की ओर ले जाती हैं।"', ref: 'नीतिवचन 21:5' },
    { text: '"सारे दशमांश भण्डार घर में ले आओ।"', ref: 'मलाकी 3:10' },
    { text: '"दो, तो तुम्हें दिया जाएगा।"', ref: 'लूका 6:38' },
    { text: '"परन्तु सन्तोष सहित भक्ति बड़ी कमाई है।"', ref: '1 तीमुथियुस 6:6' },
    { text: '"उधार लेने वाला उधार देने वाले का दास होता है।"', ref: 'नीतिवचन 22:7' },
  ],
  ar: [
    { text: '"كِلْ أَعْمَالَكَ إِلَى الرَّبِّ، فَتَتَثَبَّتَ أَفْكَارُكَ."', ref: 'أمثال 16:3' },
    { text: '"لأَنَّهُ حَيْثُ يَكُونُ كَنْزُكَ، هُنَاكَ يَكُونُ قَلْبُكَ أَيْضًا."', ref: 'متى 6:21' },
    { text: '"مَقَاصِدُ الْمُجْتَهِدِ تُفْضِي إِلَى الرِّبْحِ."', ref: 'أمثال 21:5' },
    { text: '"اِئْتُوا بِجَمِيعِ الْعُشُورِ إِلَى الْخِزَانَةِ."', ref: 'ملاخي 3:10' },
    { text: '"أَعْطُوا تُعْطَوْا."', ref: 'لوقا 6:38' },
    { text: '"لكِنَّ التَّقْوَى مَعَ الْقَنَاعَةِ تَكْسَبٌ عَظِيمٌ."', ref: '1 تيموثاوس 6:6' },
    { text: '"الْمُقْتَرِضُ عَبْدٌ لِلْمُقْرِضِ."', ref: 'أمثال 22:7' },
  ],
  ru: [
    { text: '"Предай Господу дела твои, и замыслы твои осуществятся."', ref: 'Притчи 16:3' },
    { text: '"Ибо где сокровище ваше, там будет и сердце ваше."', ref: 'Матфей 6:21' },
    { text: '"Замыслы прилежного ведут к изобилию."', ref: 'Притчи 21:5' },
    { text: '"Принесите все десятины в дом хранилища."', ref: 'Малахия 3:10' },
    { text: '"Давайте, и дастся вам."', ref: 'Лука 6:38' },
    { text: '"Великое приобретение — быть благочестивым и довольным."', ref: '1 Тимофей 6:6' },
    { text: '"Должник — слуга кредитора."', ref: 'Притчи 22:7' },
  ],
  de: [
    { text: '"Befiehl dem HERRN deine Werke, so werden deine Pläne gelingen."', ref: 'Sprüche 16:3' },
    { text: '"Denn wo dein Schatz ist, da ist auch dein Herz."', ref: 'Matthäus 6:21' },
    { text: '"Die Pläne des Fleißigen führen gewiss zum Gewinn."', ref: 'Sprüche 21:5' },
    { text: '"Bringet den ganzen Zehnten ins Vorratshaus."', ref: 'Maleachi 3:10' },
    { text: '"Gebt, so wird euch gegeben."', ref: 'Lukas 6:38' },
    { text: '"Gottseligkeit mit Genügsamkeit ist ein großer Gewinn."', ref: '1. Timotheus 6:6' },
    { text: '"Der Schuldner ist Knecht des Gläubigers."', ref: 'Sprüche 22:7' },
  ],
  it: [
    { text: '"Affida al Signore le tue opere e i tuoi progetti riusciranno."', ref: 'Proverbi 16:3' },
    { text: '"Perché dov\'è il tuo tesoro, lì sarà anche il tuo cuore."', ref: 'Matteo 6:21' },
    { text: '"I piani del diligente portano certamente all\'abbondanza."', ref: 'Proverbi 21:5' },
    { text: '"Portate tutte le decime nella casa del tesoro."', ref: 'Malachia 3:10' },
    { text: '"Date e vi sarà dato."', ref: 'Luca 6:38' },
    { text: '"La pietà con la contentezza è un grande guadagno."', ref: '1 Timoteo 6:6' },
    { text: '"Il debitore è schiavo del creditore."', ref: 'Proverbi 22:7' },
  ],
  ko: [
    { text: '"너의 행사를 여호와께 맡기라 그리하면 네가 경영하는 것이 이루어지리라."', ref: '잠언 16:3' },
    { text: '"네 보물 있는 그 곳에는 네 마음도 있느니라."', ref: '마태복음 6:21' },
    { text: '"부지런한 자의 경영은 풍부함에 이를 것이나."', ref: '잠언 21:5' },
    { text: '"만군의 여호와가 이르노라 너희의 온전한 십일조를 창고에 들여."', ref: '말라기 3:10' },
    { text: '"주라 그리하면 너희에게 줄 것이니."', ref: '누가복음 6:38' },
    { text: '"자족하는 마음이 있으면 경건은 큰 이익이 되느니라."', ref: '디모데전서 6:6' },
    { text: '"빚진 자는 채주의 종이 되느니라."', ref: '잠언 22:7' },
  ],
}

export function getDailyVerse(lang) {
  const verses = VERSES[lang] || VERSES.en
  return verses[new Date().getDay() % verses.length]
}
